### ISSUE TITLE
CLN: Refactoring MCO helper functions

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss-plugin-itwm-example#50]
The stand alone functions `get_weight_combinations`, `_int_weights` and `get_scaling_factors` in `mco.py` feel like they could be simplified using existing NumPy routines.

Whilst this is not expected to provide any major performance increase, it would simplify the code and make it easier to understand the optimisation routine that is being performed.

Additionally, since #47, we have access to a `WorkflowEvaulator` class from `force_bdss` that is currently being used in our MCO as an attribute of `WeightedEvaluator`. It may prove useful to combine these two objects together, so that `WeightedEvaulator` becomes a subclass of `WorkflowEvaluator`.

**Comment by Corwinpro** [comment]
I will have a look and think about the functions you mentioned, as well as the `Weighted` class.

**Comment by Corwinpro** [comment]
Most of the refactoring required is finished. If you know what can we do with the `WeightedOptimizer` (and `Optimizer`s in general) with regards to their relation to the MCO, please let me know.

**Comment by flongford** [comment]
Agreed, since #51 we now have a more robust way of generating the weights for an MCO run that is integrated into the new `force_bdss` classes.

The `IOptimizer` class is an interesting feature that, with some thought, could be refactored into a core `force_bdss` module. We can raise this in a separate issue.

Closing this issue since the original scope is outdated.
