### ISSUE TITLE
Port Nevergrad capabilities to Nevergrad BDSS repo

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss-plugin-itwm-example#58]
The current classes using Nevergrad library will be extremely useful for all BDSS use cases. We should port them to the ~~core `force-bdss`~~ `force-bdss-plugin-nevergrad` repo in a suitable format as soon as possible.

**Comment by Corwinpro** [comment]
This issue has been approached in [this PR](https://github.com/force-h2020/force-bdss/pull/243)

**Comment by Corwinpro** [comment]
All good now, implemented in #61
