### ISSUE TITLE
Refactor ITWM MCO class into two subclasses

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss-plugin-itwm-example#59]
The current MCO contributed by the plugin has two different optimiser modes: `WeightedOptmizer` and `NevergradOptimizer`. Both these fulfil the requirements of the `IOptimizer` interface and can be selected in the MCO model. Although it is useful to be able to easily switch between both in the WfManager, the architecture of the BDSS has been designed so that each optimiser will be contained in a separate `BaseMCO` sub class.

Refactoring each optimizer will also require us to rethink the design of the `IOptimizer` class, and whether we can express this in a more appropriate way.

**Comment by Corwinpro** [comment]
This would also require removing `WeightedOptimizer` and `NevergradOptimizer` classes: they are implemented as part of BDSS.

**Comment by Corwinpro** [comment]
Done by #61
