### ISSUE TITLE
Port CSVWriter class to BDSS

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss-plugin-itwm-example#60]
The `CSVWriter` notification listener should be ported to the `force-bdss` repo as a base class, since it is already being used in two different plugins for use cases.

**Comment by Corwinpro** [comment]
The ITWM `CSVWriter` code and logic is very similar to this code in the `force_wfmanager`: [_server_event_mainthread](https://github.com/force-h2020/force-wfmanager/blob/f9ca5b47189b1a23dff3563716e11f0bed345693/force_wfmanager/wfmanager_setup_task.py#L470)

Can we reuse and / or refactor this?

**Comment by flongford** [comment]
Closing this issue as of #62
