### ISSUE TITLE
Port OptimizerEngine class capabilities to BDSS

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss-plugin-itwm-example#63]
The `WeightedOptimizer` and `NevergradOptmizer` classes contain a useful API that can be ported to the `force-bdss` in order for additional plugins to contribute optimization techniques.

Whereas the `BaseMCO` classes are expected to contribute a complete optimisation routine for a specific application / use case, the `OptimizerEngine` classes may provide an entry point for use of functionalities within an external library / module as part the MCO.

**Comment by Corwinpro** [comment]
All good now, implemented in #61
