### ISSUE TITLE
FUTURE: Weighted optimization requires custom event types

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-bdss-plugin-itwm-example#69]
With the recent changes to the [BDSS](https://github.com/force-h2020/force-bdss/pull/274) and the [WfManager](https://github.com/force-h2020/force-wfmanager/pull/339), having `weights` as a part of the `MCOStartEvent` and `MCOProgressEvent` would require us to overload the standard `_progress_event_type` and `_start_event_type` of the MCOModel class with custom start / progress events.

We need to implement those. An example of the `WeightedMCOProgressEvent` has been discussed in [#274](https://github.com/force-h2020/force-bdss/pull/274)

**Comment by flongford** [comment]
@Corwinpro , has this been taken care of by #70 ?

**Comment by Corwinpro** [comment]
Yes, thank you, I think so.
